const listatenistas = [
  {
    idplayer: 41,
    name: "Jone",
    surname: "Inchbald",
    played: 40,
    victory: 23,
    points: 2300,
  },
  {
    idplayer: 39,
    name: "Thorny",
    surname: "Darwen",
    played: 36,
    victory: 5,
    points: 500,
  },
  {
    idplayer: 64,
    name: "Tito",
    surname: "Walcar",
    played: 15,
    victory: 13,
    points: 1300,
  },
  {
    idplayer: 55,
    name: "Greggory",
    surname: "Warnes",
    played: 20,
    victory: 4,
    points: 400,
  },
  {
    idplayer: 36,
    name: "Leif",
    surname: "Oughton",
    played: 38,
    victory: 19,
    points: 1900,
  },
  {
    idplayer: 30,
    name: "Bentley",
    surname: "Consterdine",
    played: 11,
    victory: 3,
    points: 300,
  },
  {
    idplayer: 84,
    name: "Marlin",
    surname: "McHarry",
    played: 23,
    victory: 11,
    points: 1100,
  },
  {
    idplayer: 61,
    name: "Alistair",
    surname: "Dorrance",
    played: 18,
    victory: 17,
    points: 1700,
  },
  {
    idplayer: 47,
    name: "Dylan",
    surname: "Skull",
    played: 30,
    victory: 5,
    points: 500,
  },
  {
    idplayer: 45,
    name: "Avrom",
    surname: "Eversley",
    played: 12,
    victory: 9,
    points: 900,
  },
  {
    idplayer: 44,
    name: "Uri",
    surname: "Kaszper",
    played: 14,
    victory: 3,
    points: 300,
  },
  {
    idplayer: 1,
    name: "Norrie",
    surname: "Bowes",
    played: 47,
    victory: 28,
    points: 2800,
  },
  {
    idplayer: 23,
    name: "Vernon",
    surname: "Tingley",
    played: 41,
    victory: 25,
    points: 2500,
  },
  {
    idplayer: 83,
    name: "Augie",
    surname: "Harsum",
    played: 35,
    victory: 33,
    points: 3300,
  },
  {
    idplayer: 29,
    name: "Frasco",
    surname: "Alfonzo",
    played: 25,
    victory: 11,
    points: 1100,
  },
  {
    idplayer: 99,
    name: "Madison",
    surname: "Minghi",
    played: 28,
    victory: 25,
    points: 2500,
  },
  {
    idplayer: 23,
    name: "Jehu",
    surname: "Taborre",
    played: 30,
    victory: 20,
    points: 2000,
  },
  {
    idplayer: 87,
    name: "Max",
    surname: "Gowthorpe",
    played: 28,
    victory: 26,
    points: 2600,
  },
  {
    idplayer: 90,
    name: "Bryce",
    surname: "Lomb",
    played: 35,
    victory: 29,
    points: 2900,
  },
  {
    idplayer: 11,
    name: "Bryanty",
    surname: "Iapico",
    played: 40,
    victory: 10,
    points: 1000,
  },
  {
    idplayer: 17,
    name: "Saleem",
    surname: "Syrett",
    played: 32,
    victory: 25,
    points: 2500,
  },
  {
    idplayer: 60,
    name: "Shell",
    surname: "Monsey",
    played: 18,
    victory: 3,
    points: 300,
  },
  {
    idplayer: 37,
    name: "Euell",
    surname: "Geggus",
    played: 43,
    victory: 16,
    points: 1600,
  },
  {
    idplayer: 77,
    name: "Darill",
    surname: "Brownsall",
    played: 38,
    victory: 32,
    points: 3200,
  },
  {
    idplayer: 45,
    name: "Nealon",
    surname: "Merrisson",
    played: 30,
    victory: 18,
    points: 1800,
  },
  {
    idplayer: 84,
    name: "Dimitri",
    surname: "McAlinden",
    played: 13,
    victory: 0,
    points: 0,
  },
  {
    idplayer: 31,
    name: "Esra",
    surname: "Roads",
    played: 20,
    victory: 16,
    points: 1600,
  },
  {
    idplayer: 72,
    name: "Scotti",
    surname: "Kuban",
    played: 27,
    victory: 11,
    points: 1100,
  },
  {
    idplayer: 93,
    name: "Kenny",
    surname: "Sickert",
    played: 21,
    victory: 5,
    points: 500,
  },
  {
    idplayer: 6,
    name: "Roddy",
    surname: "Kenvin",
    played: 27,
    victory: 24,
    points: 2400,
  },
  {
    idplayer: 90,
    name: "Denny",
    surname: "Wressell",
    played: 44,
    victory: 22,
    points: 2200,
  },
  {
    idplayer: 13,
    name: "Wallache",
    surname: "Carrington",
    played: 30,
    victory: 11,
    points: 1100,
  },
  {
    idplayer: 22,
    name: "Stacy",
    surname: "Dennitts",
    played: 16,
    victory: 15,
    points: 1500,
  },
  {
    idplayer: 100,
    name: "Alexandros",
    surname: "Francke",
    played: 46,
    victory: 34,
    points: 3400,
  },
  {
    idplayer: 29,
    name: "Tristan",
    surname: "Ourry",
    played: 45,
    victory: 30,
    points: 3000,
  },
  {
    idplayer: 98,
    name: "Torey",
    surname: "Tewkesbury",
    played: 49,
    victory: 42,
    points: 4200,
  },
  {
    idplayer: 2,
    name: "Hardy",
    surname: "Vigneron",
    played: 24,
    victory: 19,
    points: 1900,
  },
  {
    idplayer: 27,
    name: "Brendis",
    surname: "Crielly",
    played: 38,
    victory: 17,
    points: 1700,
  },
  {
    idplayer: 24,
    name: "Curran",
    surname: "Yurocjkin",
    played: 39,
    victory: 1,
    points: 100,
  },
  {
    idplayer: 49,
    name: "Powell",
    surname: "Evitt",
    played: 48,
    victory: 19,
    points: 1900,
  },
  {
    idplayer: 27,
    name: "Far",
    surname: "Cookman",
    played: 48,
    victory: 36,
    points: 3600,
  },
  {
    idplayer: 100,
    name: "Abbey",
    surname: "le Keux",
    played: 50,
    victory: 33,
    points: 3300,
  },
  {
    idplayer: 35,
    name: "Burtie",
    surname: "Beynke",
    played: 13,
    victory: 7,
    points: 700,
  },
  {
    idplayer: 47,
    name: "Halsey",
    surname: "Wyley",
    played: 22,
    victory: 21,
    points: 2100,
  },
  {
    idplayer: 22,
    name: "Edouard",
    surname: "MacFarlan",
    played: 49,
    victory: 14,
    points: 1400,
  },
  {
    idplayer: 27,
    name: "Chester",
    surname: "Barnaby",
    played: 20,
    victory: 11,
    points: 1100,
  },
  {
    idplayer: 89,
    name: "Peder",
    surname: "Gatward",
    played: 34,
    victory: 29,
    points: 2900,
  },
  {
    idplayer: 28,
    name: "Jarrod",
    surname: "Farington",
    played: 29,
    victory: 13,
    points: 1300,
  },
  {
    idplayer: 56,
    name: "Shaw",
    surname: "Patters",
    played: 36,
    victory: 10,
    points: 1000,
  },
  {
    idplayer: 53,
    name: "Gallard",
    surname: "Frascone",
    played: 33,
    victory: 3,
    points: 300,
  },
  {
    idplayer: 62,
    name: "Paulie",
    surname: "Clemintoni",
    played: 43,
    victory: 11,
    points: 1100,
  },
  {
    idplayer: 7,
    name: "Wayland",
    surname: "Arnault",
    played: 28,
    victory: 10,
    points: 1000,
  },
  {
    idplayer: 6,
    name: "Gordie",
    surname: "Creebo",
    played: 47,
    victory: 7,
    points: 700,
  },
  {
    idplayer: 64,
    name: "Fabian",
    surname: "Gorst",
    played: 44,
    victory: 38,
    points: 3800,
  },
  {
    idplayer: 89,
    name: "Aldon",
    surname: "Cowing",
    played: 32,
    victory: 17,
    points: 1700,
  },
  {
    idplayer: 53,
    name: "Ronnie",
    surname: "Huffadine",
    played: 50,
    victory: 26,
    points: 2600,
  },
  {
    idplayer: 62,
    name: "Lawry",
    surname: "Tommen",
    played: 13,
    victory: 5,
    points: 500,
  },
  {
    idplayer: 54,
    name: "Reidar",
    surname: "Dunham",
    played: 16,
    victory: 16,
    points: 1600,
  },
  {
    idplayer: 39,
    name: "Mattheus",
    surname: "Hackworthy",
    played: 49,
    victory: 34,
    points: 3400,
  },
  {
    idplayer: 13,
    name: "Nickolai",
    surname: "Darben",
    played: 34,
    victory: 4,
    points: 400,
  },
  {
    idplayer: 71,
    name: "Orville",
    surname: "Litherborough",
    played: 17,
    victory: 11,
    points: 1100,
  },
  {
    idplayer: 92,
    name: "Tobiah",
    surname: "Nuccii",
    played: 38,
    victory: 28,
    points: 2800,
  },
  {
    idplayer: 71,
    name: "Dylan",
    surname: "Sallings",
    played: 48,
    victory: 18,
    points: 1800,
  },
  {
    idplayer: 20,
    name: "Winslow",
    surname: "Nettleship",
    played: 17,
    victory: 16,
    points: 1600,
  },
  {
    idplayer: 19,
    name: "Trevor",
    surname: "Lanchester",
    played: 38,
    victory: 25,
    points: 2500,
  },
  {
    idplayer: 9,
    name: "Rollin",
    surname: "Smitherham",
    played: 18,
    victory: 13,
    points: 1300,
  },
  {
    idplayer: 27,
    name: "Drud",
    surname: "Domoney",
    played: 24,
    victory: 11,
    points: 1100,
  },
  {
    idplayer: 56,
    name: "Christie",
    surname: "Fassbindler",
    played: 44,
    victory: 28,
    points: 2800,
  },
  {
    idplayer: 65,
    name: "Shepard",
    surname: "Parke",
    played: 33,
    victory: 13,
    points: 1300,
  },
  {
    idplayer: 93,
    name: "Barnard",
    surname: "Burner",
    played: 42,
    victory: 37,
    points: 3700,
  },
  {
    idplayer: 37,
    name: "Reuven",
    surname: "Swaddle",
    played: 27,
    victory: 6,
    points: 600,
  },
  {
    idplayer: 31,
    name: "Willard",
    surname: "Wragg",
    played: 26,
    victory: 3,
    points: 300,
  },
  {
    idplayer: 11,
    name: "Salvatore",
    surname: "Houldcroft",
    played: 11,
    victory: 4,
    points: 400,
  },
  {
    idplayer: 79,
    name: "Izzy",
    surname: "Merveille",
    played: 35,
    victory: 30,
    points: 3000,
  },
  {
    idplayer: 26,
    name: "Teodorico",
    surname: "Morilla",
    played: 15,
    victory: 6,
    points: 600,
  },
  {
    idplayer: 16,
    name: "Aldis",
    surname: "Benson",
    played: 41,
    victory: 36,
    points: 3600,
  },
  {
    idplayer: 92,
    name: "Hirsch",
    surname: "Inkle",
    played: 20,
    victory: 5,
    points: 500,
  },
  {
    idplayer: 63,
    name: "Barrett",
    surname: "Potzold",
    played: 47,
    victory: 37,
    points: 3700,
  },
  {
    idplayer: 1,
    name: "Garrek",
    surname: "Syne",
    played: 24,
    victory: 20,
    points: 2000,
  },
  {
    idplayer: 42,
    name: "Kleon",
    surname: "Struan",
    played: 20,
    victory: 2,
    points: 200,
  },
  {
    idplayer: 75,
    name: "Bogey",
    surname: "Copeman",
    played: 47,
    victory: 15,
    points: 1500,
  },
  {
    idplayer: 51,
    name: "Gerard",
    surname: "Simm",
    played: 32,
    victory: 15,
    points: 1500,
  },
  {
    idplayer: 72,
    name: "Alfy",
    surname: "Gaines",
    played: 36,
    victory: 3,
    points: 300,
  },
  {
    idplayer: 30,
    name: "Jarid",
    surname: "Athridge",
    played: 41,
    victory: 11,
    points: 1100,
  },
  {
    idplayer: 97,
    name: "Arthur",
    surname: "Wrenn",
    played: 25,
    victory: 1,
    points: 100,
  },
  {
    idplayer: 49,
    name: "Aguie",
    surname: "Screach",
    played: 45,
    victory: 16,
    points: 1600,
  },
  {
    idplayer: 99,
    name: "Thorvald",
    surname: "Angier",
    played: 40,
    victory: 21,
    points: 2100,
  },
  {
    idplayer: 23,
    name: "Culley",
    surname: "Zavattieri",
    played: 48,
    victory: 3,
    points: 300,
  },
  {
    idplayer: 46,
    name: "Mannie",
    surname: "Rosenkrantz",
    played: 34,
    victory: 2,
    points: 200,
  },
  {
    idplayer: 10,
    name: "Cordy",
    surname: "Kennefick",
    played: 14,
    victory: 4,
    points: 400,
  },
  {
    idplayer: 74,
    name: "Trevar",
    surname: "Kermannes",
    played: 32,
    victory: 32,
    points: 3200,
  },
  {
    idplayer: 4,
    name: "Antonin",
    surname: "Frantzeni",
    played: 36,
    victory: 23,
    points: 2300,
  },
  {
    idplayer: 32,
    name: "Lennie",
    surname: "Currington",
    played: 28,
    victory: 16,
    points: 1600,
  },
  {
    idplayer: 12,
    name: "Mike",
    surname: "Tiddy",
    played: 42,
    victory: 9,
    points: 900,
  },
  {
    idplayer: 26,
    name: "Winslow",
    surname: "Polgreen",
    played: 13,
    victory: 1,
    points: 100,
  },
  {
    idplayer: 41,
    name: "Millard",
    surname: "Spering",
    played: 16,
    victory: 8,
    points: 800,
  },
  {
    idplayer: 2,
    name: "Sigismondo",
    surname: "Byrch",
    played: 34,
    victory: 29,
    points: 2900,
  },
  {
    idplayer: 6,
    name: "Fax",
    surname: "Zohrer",
    played: 28,
    victory: 22,
    points: 2200,
  },
  {
    idplayer: 17,
    name: "Neville",
    surname: "Daintree",
    played: 50,
    victory: 33,
    points: 3300,
  },
  {
    idplayer: 94,
    name: "Emory",
    surname: "Pagan",
    played: 22,
    victory: 7,
    points: 700,
  },
];
