const dataprovincias = [
  {
    id: "AB",
    nombre: "Albacete",
    comunidad: "Castilla - La Mancha",
    hab_mil: 396,
    x: 428,
    y: 285,
  },
  {
    id: "A",
    nombre: "Alicante",
    comunidad: "Comunitat Valenciana",
    hab_mil: 1853,
    x: 506,
    y: 304,
  },
  {
    id: "AL",
    nombre: "Almería",
    comunidad: "Andalucía",
    hab_mil: 689,
    x: 408,
    y: 375,
  },
  {
    id: "AV",
    nombre: "Ávila",
    comunidad: "Castilla y León",
    hab_mil: 166,
    x: 264,
    y: 189,
  },
  {
    id: "BA",
    nombre: "Badajoz",
    comunidad: "Extremadura",
    hab_mil: 687,
    x: 198,
    y: 292,
  },
  {
    id: "PM",
    nombre: "Islas Baleares",
    comunidad: "Illes Balears",
    hab_mil: 1122,
    x: 699,
    y: 244,
  },
  {
    id: "B",
    nombre: "Barcelona",
    comunidad: "Cataluña",
    hab_mil: 5435,
    x: 648,
    y: 126,
  },
  {
    id: "CC",
    nombre: "Cáceres",
    comunidad: "Extremadura",
    hab_mil: 407,
    x: 196,
    y: 237,
  },
  {
    id: "CR",
    nombre: "Ciudad Real",
    comunidad: "Castilla - La Mancha",
    hab_mil: 516,
    x: 326,
    y: 280,
  },
  {
    id: "CO",
    nombre: "Córdoba",
    comunidad: "Andalucía",
    hab_mil: 797,
    x: 271,
    y: 331,
  },
  {
    id: "C",
    nombre: "La Coruña",
    comunidad: "Galicia",
    hab_mil: 1130,
    x: 69,
    y: 49,
  },
  {
    id: "GU",
    nombre: "Guadalajara",
    comunidad: "Castilla - La Mancha",
    hab_mil: 255,
    x: 392,
    y: 176,
  },
  {
    id: "SS",
    nombre: "Guipúzcoa",
    comunidad: "País Vasco",
    hab_mil: 707,
    x: 416,
    y: 48,
  },
  {
    id: "J",
    nombre: "Jaén",
    comunidad: "Andalucía",
    hab_mil: 654,
    x: 347,
    y: 330,
  },
  {
    id: "LE",
    nombre: "León",
    comunidad: "Castilla y León",
    hab_mil: 482,
    x: 214,
    y: 77,
  },
  {
    id: "L",
    nombre: "Lleida",
    comunidad: "Cataluña",
    hab_mil: 431,
    x: 596,
    y: 109,
  },
  {
    id: "M",
    nombre: "Madrid",
    comunidad: "Comunidad de Madrid",
    hab_mil: 6377,
    x: 332,
    y: 194,
  },
  {
    id: "MA",
    nombre: "Málaga",
    comunidad: "Andalucía",
    hab_mil: 1626,
    x: 276,
    y: 396,
  },
  {
    id: "NA",
    nombre: "Navarra",
    comunidad: "Comunidad Foral de Navarra",
    hab_mil: 636,
    x: 447,
    y: 74,
  },
  {
    id: "OR",
    nombre: "Orense",
    comunidad: "Galicia",
    hab_mil: 320,
    x: 117,
    y: 100,
  },
  {
    id: "O",
    nombre: "Asturias",
    comunidad: "Asturias, Principado de",
    hab_mil: 1054,
    x: 206,
    y: 40,
  },
  {
    id: "GC",
    nombre: "Las Palmas",
    comunidad: "Canarias",
    hab_mil: 1103,
    x: 172,
    y: 402,
  },
  {
    id: "PO",
    nombre: "Pontevedra",
    comunidad: "Galicia",
    hab_mil: 949,
    x: 69,
    y: 87,
  },
  {
    id: "S",
    nombre: "Cantabria",
    comunidad: "Cantabria",
    hab_mil: 586,
    x: 314,
    y: 45,
  },
  {
    id: "SG",
    nombre: "Segovia",
    comunidad: "Castilla y León",
    hab_mil: 159,
    x: 313,
    y: 156,
  },
  {
    id: "SO",
    nombre: "Soria",
    comunidad: "Castilla y León",
    hab_mil: 92,
    x: 394,
    y: 132,
  },
  {
    id: "T",
    nombre: "Tarragona",
    comunidad: "Cataluña",
    hab_mil: 793,
    x: 583,
    y: 161,
  },
  {
    id: "TO",
    nombre: "Toledo",
    comunidad: "Castilla - La Mancha",
    hab_mil: 693,
    x: 308,
    y: 232,
  },
  {
    id: "V",
    nombre: "Valencia",
    comunidad: "Comunitat Valenciana",
    hab_mil: 2522,
    x: 493,
    y: 255,
  },
  {
    id: "VA",
    nombre: "Valladolid",
    comunidad: "Castilla y León",
    hab_mil: 528,
    x: 269,
    y: 131,
  },
  {
    id: "Z",
    nombre: "Zaragoza",
    comunidad: "Aragón",
    hab_mil: 967,
    x: 479,
    y: 132,
  },
];
