const exitos = [
  {"artist_name":"Michael Jackson","song_name":"Billie Jean","album_name":"Thriller","release_year":1982,"group_or_solo":"Solo","genre":"Pop","ranking":1},
  {"artist_name":"Queen","song_name":"Bohemian Rhapsody","album_name":"A Night at the Opera","release_year":1975,"group_or_solo":"Group","genre":"Rock","ranking":2},
  {"artist_name":"The Beatles","song_name":"Hey Jude","album_name":null,"release_year":1968,"group_or_solo":"Group","genre":"Rock","ranking":3},
  {"artist_name":"Madonna","song_name":"Like a Prayer","album_name":"Like a Prayer","release_year":1989,"group_or_solo":"Solo","genre":"Pop","ranking":4},
  {"artist_name":"Nirvana","song_name":"Smells Like Teen Spirit","album_name":"Nevermind","release_year":1991,"group_or_solo":"Group","genre":"Grunge|Rock","ranking":5},
  {"artist_name":"Adele","song_name":"Rolling in the Deep","album_name":"21","release_year":2010,"group_or_solo":"Solo","genre":"Pop|Soul","ranking":6},
  {"artist_name":"U2","song_name":"With or Without You","album_name":"The Joshua Tree","release_year":1987,"group_or_solo":"Group","genre":"Rock","ranking":7},
  {"artist_name":"Prince","song_name":"Purple Rain","album_name":"Purple Rain","release_year":1984,"group_or_solo":"Solo","genre":"Pop|Rock","ranking":8},
  {"artist_name":"Radiohead","song_name":"Creep","album_name":"Pablo Honey","release_year":1992,"group_or_solo":"Group","genre":"Alternative Rock","ranking":9},
  {"artist_name":"Bob Dylan","song_name":"Like a Rolling Stone","album_name":"Highway 61 Revisited","release_year":1965,"group_or_solo":"Solo","genre":"Folk Rock","ranking":10},
  {"artist_name":"Beyoncé","song_name":"Single Ladies","album_name":"I Am... Sasha Fierce","release_year":2008,"group_or_solo":"Solo","genre":"Pop|R&B","ranking":11},
  {"artist_name":"Coldplay","song_name":"Fix You","album_name":"X&Y","release_year":2005,"group_or_solo":"Group","genre":"Alternative Rock","ranking":12},
  {"artist_name":"Elvis Presley","song_name":"Can't Help Falling in Love","album_name":"Blue Hawaii","release_year":1961,"group_or_solo":"Solo","genre":"Pop","ranking":13},
  {"artist_name":"The Rolling Stones","song_name":"Satisfaction","album_name":"Out of Our Heads","release_year":1965,"group_or_solo":"Group","genre":"Rock","ranking":14},
  {"artist_name":"Rihanna","song_name":"Umbrella","album_name":"Good Girl Gone Bad","release_year":2007,"group_or_solo":"Solo","genre":"Pop|R&B","ranking":15},
  {"artist_name":"Pink Floyd","song_name":"Another Brick in the Wall","album_name":"The Wall","release_year":1979,"group_or_solo":"Group","genre":"Progressive Rock","ranking":16},
  {"artist_name":"Bruno Mars","song_name":"Uptown Funk","album_name":null,"release_year":2014,"group_or_solo":"Solo","genre":"Funk|Pop","ranking":17},
  {"artist_name":"Eminem","song_name":"Lose Yourself","album_name":"8 Mile","release_year":2002,"group_or_solo":"Solo","genre":"Hip Hop","ranking":18},
  {"artist_name":"Daft Punk","song_name":"Get Lucky","album_name":"Random Access Memories","release_year":2013,"group_or_solo":"Group","genre":"Electronic","ranking":19},
  {"artist_name":"Whitney Houston","song_name":"I Will Always Love You","album_name":"The Bodyguard","release_year":1992,"group_or_solo":"Solo","genre":"Pop|Soul","ranking":20},
  {"artist_name":"Taylor Swift","song_name":"Shake It Off","album_name":"1989","release_year":2014,"group_or_solo":"Solo","genre":"Pop","ranking":21},
  {"artist_name":"The Weeknd","song_name":"Blinding Lights","album_name":"After Hours","release_year":2019,"group_or_solo":"Solo","genre":"Pop|Synthwave","ranking":22},
  {"artist_name":"Metallica","song_name":"Enter Sandman","album_name":"Metallica","release_year":1991,"group_or_solo":"Group","genre":"Heavy Metal","ranking":23},
  {"artist_name":"Amy Winehouse","song_name":"Back to Black","album_name":"Back to Black","release_year":2006,"group_or_solo":"Solo","genre":"Soul|R&B","ranking":24},
  {"artist_name":"Oasis","song_name":"Wonderwall","album_name":"(What's the Story) Morning Glory?","release_year":1995,"group_or_solo":"Group","genre":"Britpop","ranking":25},
  {"artist_name":"David Bowie","song_name":"Heroes","album_name":"Heroes","release_year":1977,"group_or_solo":"Solo","genre":"Art Rock","ranking":26},
  {"artist_name":"Linkin Park","song_name":"In the End","album_name":"Hybrid Theory","release_year":2000,"group_or_solo":"Group","genre":"Nu Metal","ranking":27},
  {"artist_name":"Red Hot Chili Peppers","song_name":"Californication","album_name":"Californication","release_year":1999,"group_or_solo":"Group","genre":"Alternative Rock","ranking":28},
  {"artist_name":"Frank Sinatra","song_name":"My Way","album_name":null,"release_year":null,"group_or_solo":"Solo","genre":"Jazz|Pop","ranking":29},
  {"artist_name":"Kendrick Lamar","song_name":"HUMBLE.","album_name":"DAMN.","release_year":2017,"group_or_solo":"Solo","genre":"Hip Hop","ranking":30},
  {"artist_name":"Drake","song_name":"God's Plan","album_name":"Scorpion","release_year":2018,"group_or_solo":"Solo","genre":"Hip Hop","ranking":31},
  {"artist_name":"Lady Gaga","song_name":"Bad Romance","album_name":"The Fame Monster","release_year":2009,"group_or_solo":"Solo","genre":"Pop","ranking":32},
  {"artist_name":"The Killers","song_name":"Mr. Brightside","album_name":"Hot Fuss","release_year":2003,"group_or_solo":"Group","genre":"Alternative Rock","ranking":33},
  {"artist_name":"AC/DC","song_name":"Back in Black","album_name":"Back in Black","release_year":1980,"group_or_solo":"Group","genre":"Hard Rock","ranking":34},
  {"artist_name":"Shakira","song_name":"Hips Don't Lie","album_name":"Oral Fixation Vol. 2","release_year":2006,"group_or_solo":"Solo","genre":"Pop|Latin","ranking":35},
  {"artist_name":"Bon Jovi","song_name":"Livin' on a Prayer","album_name":"Slippery When Wet","release_year":1986,"group_or_solo":"Group","genre":"Rock","ranking":36},
  {"artist_name":"Ed Sheeran","song_name":"Shape of You","album_name":"÷","release_year":2017,"group_or_solo":"Solo","genre":"Pop","ranking":37},
  {"artist_name":"Guns N' Roses","song_name":"Sweet Child o' Mine","album_name":"Appetite for Destruction","release_year":1987,"group_or_solo":"Group","genre":"Hard Rock","ranking":38},
  {"artist_name":"Billie Eilish","song_name":"bad guy","album_name":"When We All Fall Asleep, Where Do We Go?","release_year":2019,"group_or_solo":"Solo","genre":"Pop","ranking":39},
  {"artist_name":"Journey","song_name":"Don't Stop Believin'","album_name":"Escape","release_year":1981,"group_or_solo":"Group","genre":"Rock","ranking":40},
  {"artist_name":"Maroon 5","song_name":"This Love","album_name":"Songs About Jane","release_year":2002,"group_or_solo":"Group","genre":"Pop Rock","ranking":41},
  {"artist_name":"The Police","song_name":"Every Breath You Take","album_name":"Synchronicity","release_year":1983,"group_or_solo":"Group","genre":"Rock","ranking":42},
  {"artist_name":"Sia","song_name":"Chandelier","album_name":"1000 Forms of Fear","release_year":2014,"group_or_solo":"Solo","genre":"Pop","ranking":43},
  {"artist_name":"Arctic Monkeys","song_name":"Do I Wanna Know?","album_name":"AM","release_year":2013,"group_or_solo":"Group","genre":"Indie Rock","ranking":44},
  {"artist_name":"Foo Fighters","song_name":"Everlong","album_name":"The Colour and the Shape","release_year":1997,"group_or_solo":"Group","genre":"Alternative Rock","ranking":45},
  {"artist_name":"Lana Del Rey","song_name":"Summertime Sadness","album_name":"Born to Die","release_year":2012,"group_or_solo":"Solo","genre":"Indie Pop","ranking":46},
  {"artist_name":"The Smiths","song_name":"There Is a Light That Never Goes Out","album_name":"The Queen Is Dead","release_year":1986,"group_or_solo":"Group","genre":"Indie Rock","ranking":47},
  {"artist_name":"ABBA","song_name":"Dancing Queen","album_name":"Arrival","release_year":1976,"group_or_solo":"Group","genre":"Pop","ranking":48},
  {"artist_name":"The Doors","song_name":"Light My Fire","album_name":"The Doors","release_year":1967,"group_or_solo":"Group","genre":"Psychedelic Rock","ranking":49},
  {"artist_name":"Camila Cabello","song_name":"Havana","album_name":null,"release_year":2017,"group_or_solo":"Solo","genre":"Pop","ranking":50},
  {"artist_name":"Rosalía","song_name":"Malamente","album_name":"El Mal Querer","release_year":2018,"group_or_solo":"Solo","genre":"Pop|Flamenco","ranking":151},
  {"artist_name":"C. Tangana","song_name":"Tú me dejaste de querer","album_name":"El Madrileño","release_year":2021,"group_or_solo":"Solo","genre":"Hip Hop|Latin","ranking":152},
  {"artist_name":"Héroes del Silencio","song_name":"Entre dos tierras","album_name":"Senderos de Traición","release_year":1990,"group_or_solo":"Group","genre":"Rock","ranking":153},
  {"artist_name":"Mecano","song_name":"Hijo de la Luna","album_name":"Entre el Cielo y el Suelo","release_year":1986,"group_or_solo":"Group","genre":"Pop","ranking":154},
  {"artist_name":"Joaquín Sabina","song_name":"19 días y 500 noches","album_name":"19 días y 500 noches","release_year":1999,"group_or_solo":"Solo","genre":"Singer-Songwriter","ranking":155},
  {"artist_name":"Estopa","song_name":"La Raja de Tu Falda","album_name":"Estopa","release_year":1999,"group_or_solo":"Group","genre":"Rumba Rock","ranking":156},
  {"artist_name":"Vetusta Morla","song_name":"Copenhague","album_name":"Un día en el mundo","release_year":2008,"group_or_solo":"Group","genre":"Indie Rock","ranking":157},
  {"artist_name":"Alejandro Sanz","song_name":"Corazón Partío","album_name":"Más","release_year":1997,"group_or_solo":"Solo","genre":"Pop","ranking":158},
  {"artist_name":"Extremoduro","song_name":"So payaso","album_name":"Agila","release_year":1996,"group_or_solo":"Group","genre":"Rock","ranking":159},
  {"artist_name":"La Oreja de Van Gogh","song_name":"Rosas","album_name":"Lo que te conté mientras te hacías la dormida","release_year":2003,"group_or_solo":"Group","genre":"Pop","ranking":160},
  {"artist_name":"Nach","song_name":"Efectos Vocales","album_name":"Poesía Difusa","release_year":2003,"group_or_solo":"Solo","genre":"Hip Hop","ranking":161},
  {"artist_name":"Love of Lesbian","song_name":"Allí donde solíamos gritar","album_name":"1999","release_year":2009,"group_or_solo":"Group","genre":"Indie Pop","ranking":162},
  {"artist_name":"Dover","song_name":"Devil Came to Me","album_name":"Devil Came to Me","release_year":1997,"group_or_solo":"Group","genre":"Alternative Rock","ranking":163},
  {"artist_name":"Izál","song_name":"Copacabana","album_name":"Copacabana","release_year":2015,"group_or_solo":"Group","genre":"Indie Pop","ranking":164},
  {"artist_name":"Pereza","song_name":"Princesas","album_name":"Animales","release_year":2005,"group_or_solo":"Group","genre":"Rock","ranking":165},
  {"artist_name":"Fangoria","song_name":"Ni tú ni nadie","album_name":null,"release_year":null,"group_or_solo":"Group","genre":"Pop","ranking":166},
  {"artist_name":"Raphael","song_name":"Mi gran noche","album_name":null,"release_year":1967,"group_or_solo":"Solo","genre":"Pop","ranking":167},
  {"artist_name":"Nino Bravo","song_name":"Libre","album_name":null,"release_year":1972,"group_or_solo":"Solo","genre":"Pop","ranking":168},
  {"artist_name":"Los Secretos","song_name":"Déjame","album_name":"Los Secretos","release_year":1980,"group_or_solo":"Group","genre":"Pop Rock","ranking":169},
  {"artist_name":"Duncan Dhu","song_name":"En algún lugar","album_name":"El grito del tiempo","release_year":1987,"group_or_solo":"Group","genre":"Pop Rock","ranking":170},
  {"artist_name":"Bad Bunny","song_name":"Tití Me Preguntó","album_name":"Un Verano Sin Ti","release_year":2022,"group_or_solo":"Solo","genre":"Reggaeton","ranking":171},
  {"artist_name":"Shakira","song_name":"Ojos Así","album_name":"Dónde Están los Ladrones","release_year":1998,"group_or_solo":"Solo","genre":"Pop|Latin","ranking":172},
  {"artist_name":"Daddy Yankee","song_name":"Gasolina","album_name":"Barrio Fino","release_year":2004,"group_or_solo":"Solo","genre":"Reggaeton","ranking":173},
  {"artist_name":"Karol G","song_name":"Provenza","album_name":"Mañana Será Bonito","release_year":2022,"group_or_solo":"Solo","genre":"Latin Pop","ranking":174},
  {"artist_name":"BTS","song_name":"Dynamite","album_name":null,"release_year":2020,"group_or_solo":"Group","genre":"K-Pop","ranking":175},
  {"artist_name":"BLACKPINK","song_name":"How You Like That","album_name":"The Album","release_year":2020,"group_or_solo":"Group","genre":"K-Pop","ranking":176},
  {"artist_name":"IU","song_name":"Love Poem","album_name":"Love Poem","release_year":2019,"group_or_solo":"Solo","genre":"K-Pop","ranking":177},
  {"artist_name":"Stromae","song_name":"Alors on danse","album_name":"Cheese","release_year":2010,"group_or_solo":"Solo","genre":"Electronic|Hip Hop","ranking":178},
  {"artist_name":"Daft Punk","song_name":"One More Time","album_name":"Discovery","release_year":2000,"group_or_solo":"Group","genre":"Electronic","ranking":179},
  {"artist_name":"Aya Nakamura","song_name":"Djadja","album_name":"Nakamura","release_year":2018,"group_or_solo":"Solo","genre":"Pop|R&B","ranking":180},
  {"artist_name":"Rammstein","song_name":"Du Hast","album_name":"Sehnsucht","release_year":1997,"group_or_solo":"Group","genre":"Industrial Metal","ranking":181},
  {"artist_name":"Falco","song_name":"Rock Me Amadeus","album_name":"Falco 3","release_year":1985,"group_or_solo":"Solo","genre":"Pop","ranking":182},
  {"artist_name":"Manu Chao","song_name":"Clandestino","album_name":"Clandestino","release_year":1998,"group_or_solo":"Solo","genre":"World Music","ranking":183},
  {"artist_name":"Juanes","song_name":"A Dios le Pido","album_name":"Un Día Normal","release_year":2002,"group_or_solo":"Solo","genre":"Latin Rock","ranking":184},
  {"artist_name":"Bob Marley & The Wailers","song_name":"No Woman, No Cry","album_name":null,"release_year":1974,"group_or_solo":"Group","genre":"Reggae","ranking":185},
  {"artist_name":"Burning Spear","song_name":"Marcus Garvey","album_name":"Marcus Garvey","release_year":1975,"group_or_solo":"Solo","genre":"Reggae","ranking":186},
  {"artist_name":"Angèle","song_name":"Balance ton quoi","album_name":"Brol","release_year":2018,"group_or_solo":"Solo","genre":"Pop","ranking":187},
  {"artist_name":"Christine and the Queens","song_name":"Tilted","album_name":"Chaleur Humaine","release_year":2014,"group_or_solo":"Solo","genre":"Pop","ranking":188},
  {"artist_name":"Drake","song_name":"One Dance","album_name":"Views","release_year":2016,"group_or_solo":"Solo","genre":"Hip Hop","ranking":189},
  {"artist_name":"The Weeknd","song_name":"Starboy","album_name":"Starboy","release_year":2016,"group_or_solo":"Solo","genre":"Pop|R&B","ranking":190},
  {"artist_name":"AC/DC","song_name":"Thunderstruck","album_name":"The Razors Edge","release_year":1990,"group_or_solo":"Group","genre":"Hard Rock","ranking":191},
  {"artist_name":"Tame Impala","song_name":"The Less I Know the Better","album_name":"Currents","release_year":2015,"group_or_solo":"Solo","genre":"Psychedelic Pop","ranking":192},
  {"artist_name":"Youssou N'Dour","song_name":"7 Seconds","album_name":"Wommat","release_year":1994,"group_or_solo":"Solo","genre":"World Music","ranking":193},
  {"artist_name":"Salif Keita","song_name":"Yamore","album_name":null,"release_year":null,"group_or_solo":"Solo","genre":"World Music","ranking":194},
  {"artist_name":"A.R. Rahman","song_name":"Jai Ho","album_name":"Slumdog Millionaire Soundtrack","release_year":2008,"group_or_solo":"Solo","genre":"Soundtrack","ranking":195},
  {"artist_name":"Arijit Singh","song_name":"Tum Hi Ho","album_name":"Aashiqui 2","release_year":2013,"group_or_solo":"Solo","genre":"Bollywood","ranking":196},
  {"artist_name":"The Hu","song_name":"Wolf Totem","album_name":"The Gereg","release_year":2019,"group_or_solo":"Group","genre":"Folk Metal","ranking":197},
  {"artist_name":"Sigur Rós","song_name":"Hoppípolla","album_name":"Takk...","release_year":2005,"group_or_solo":"Group","genre":"Post-Rock","ranking":198},
  {"artist_name":"Ricky Martin","song_name":"Livin' la Vida Loca","album_name":"Ricky Martin","release_year":1999,"group_or_solo":"Solo","genre":"Latin Pop","ranking":199},
  {"artist_name":"Céline Dion","song_name":"My Heart Will Go On","album_name":"Titanic Soundtrack","release_year":1997,"group_or_solo":"Solo","genre":"Pop","ranking":200},
  {"artist_name":"Taylor Swift","song_name":"Shake It Off","album_name":"1989","release_year":2014,"group_or_solo":"Solo","genre":"Pop","ranking":201},
  {"artist_name":"Ed Sheeran","song_name":"Shape of You","album_name":"÷","release_year":2017,"group_or_solo":"Solo","genre":"Pop","ranking":202},
  {"artist_name":"Adele","song_name":"Rolling in the Deep","album_name":"21","release_year":2011,"group_or_solo":"Solo","genre":"Pop|Soul","ranking":203},
  {"artist_name":"Coldplay","song_name":"Viva la Vida","album_name":"Viva la Vida or Death and All His Friends","release_year":2008,"group_or_solo":"Group","genre":"Alternative Rock","ranking":204},
  {"artist_name":"Rosalía","song_name":"Despechá","album_name":null,"release_year":2022,"group_or_solo":"Solo","genre":"Latin Pop","ranking":205},
  {"artist_name":"J Balvin","song_name":"Mi Gente","album_name":"Vibras","release_year":2017,"group_or_solo":"Solo","genre":"Reggaeton","ranking":206},
  {"artist_name":"Anitta","song_name":"Envolver","album_name":"Versions of Me","release_year":2022,"group_or_solo":"Solo","genre":"Latin Pop","ranking":207},
  {"artist_name":"Drake","song_name":"God's Plan","album_name":"Scorpion","release_year":2018,"group_or_solo":"Solo","genre":"Hip Hop","ranking":208},
  {"artist_name":"Kendrick Lamar","song_name":"HUMBLE.","album_name":"DAMN.","release_year":2017,"group_or_solo":"Solo","genre":"Hip Hop","ranking":209},
  {"artist_name":"Eminem","song_name":"Lose Yourself","album_name":"8 Mile Soundtrack","release_year":2002,"group_or_solo":"Solo","genre":"Hip Hop","ranking":210},
  {"artist_name":"Metallica","song_name":"Enter Sandman","album_name":"Metallica","release_year":1991,"group_or_solo":"Group","genre":"Heavy Metal","ranking":211},
  {"artist_name":"Iron Maiden","song_name":"The Trooper","album_name":"Piece of Mind","release_year":1983,"group_or_solo":"Group","genre":"Heavy Metal","ranking":212},
  {"artist_name":"Linkin Park","song_name":"Numb","album_name":"Meteora","release_year":2003,"group_or_solo":"Group","genre":"Alternative Metal","ranking":213},
  {"artist_name":"ABBA","song_name":"Dancing Queen","album_name":"Arrival","release_year":1976,"group_or_solo":"Group","genre":"Pop","ranking":214},
  {"artist_name":"Roxette","song_name":"It Must Have Been Love","album_name":"Joyride","release_year":1990,"group_or_solo":"Group","genre":"Pop","ranking":215},
  {"artist_name":"U2","song_name":"I Still Haven't Found What I'm Looking For","album_name":"The Joshua Tree","release_year":1987,"group_or_solo":"Group","genre":"Rock","ranking":216},
  {"artist_name":"The Cranberries","song_name":"Zombie","album_name":"No Need to Argue","release_year":1994,"group_or_solo":"Group","genre":"Alternative Rock","ranking":217},
  {"artist_name":"Bob Dylan","song_name":"Like a Rolling Stone","album_name":"Highway 61 Revisited","release_year":1965,"group_or_solo":"Solo","genre":"Folk Rock","ranking":218},
  {"artist_name":"Johnny Cash","song_name":"Hurt","album_name":"American IV","release_year":2002,"group_or_solo":"Solo","genre":"Country","ranking":219},
  {"artist_name":"Daddy Yankee","song_name":"Con Calma","album_name":null,"release_year":2019,"group_or_solo":"Solo","genre":"Reggaeton","ranking":220},
  {"artist_name":"Ozuna","song_name":"Se Preparó","album_name":"Odisea","release_year":2017,"group_or_solo":"Solo","genre":"Reggaeton","ranking":221},
  {"artist_name":"Burna Boy","song_name":"Ye","album_name":"Outside","release_year":2018,"group_or_solo":"Solo","genre":"Afrobeats","ranking":222},
  {"artist_name":"Wizkid","song_name":"Essence","album_name":"Made in Lagos","release_year":2020,"group_or_solo":"Solo","genre":"Afrobeats","ranking":223},
  {"artist_name":"Ryuichi Sakamoto","song_name":"Merry Christmas Mr. Lawrence","album_name":null,"release_year":1983,"group_or_solo":"Solo","genre":"Instrumental","ranking":224},
  {"artist_name":"Joe Hisaishi","song_name":"One Summer's Day","album_name":"Spirited Away Soundtrack","release_year":2001,"group_or_solo":"Solo","genre":"Soundtrack","ranking":225},
  {"artist_name":"The Beatles","song_name":"Let It Be","album_name":"Let It Be","release_year":1970,"group_or_solo":"Group","genre":"Rock","ranking":226},
  {"artist_name":"Queen","song_name":"Don't Stop Me Now","album_name":"Jazz","release_year":1978,"group_or_solo":"Group","genre":"Rock","ranking":227},
  {"artist_name":"Santana","song_name":"Smooth","album_name":"Supernatural","release_year":1999,"group_or_solo":"Group","genre":"Latin Rock","ranking":228},
  {"artist_name":"Maná","song_name":"Rayando el Sol","album_name":"Falta Amor","release_year":1989,"group_or_solo":"Group","genre":"Latin Rock","ranking":229},
  {"artist_name":"Nusrat Fateh Ali Khan","song_name":"Mustt Mustt","album_name":null,"release_year":1990,"group_or_solo":"Solo","genre":"Qawwali","ranking":230},
  {"artist_name":"Lorde","song_name":"Royals","album_name":"Pure Heroine","release_year":2013,"group_or_solo":"Solo","genre":"Pop","ranking":231},
  {"artist_name":"Pharrell Williams","song_name":"Happy","album_name":"G I R L","release_year":2014,"group_or_solo":"Solo","genre":"Pop","ranking":232},
  {"artist_name":"Sia","song_name":"Chandelier","album_name":"1000 Forms of Fear","release_year":2014,"group_or_solo":"Solo","genre":"Pop","ranking":233},
  {"artist_name":"Gotye","song_name":"Somebody That I Used to Know","album_name":"Making Mirrors","release_year":2011,"group_or_solo":"Solo","genre":"Indie Pop","ranking":234},
  {"artist_name":"Måneskin","song_name":"Zitti e buoni","album_name":"Teatro d'ira: Vol. I","release_year":2021,"group_or_solo":"Group","genre":"Rock","ranking":235},
  {"artist_name":"Daddy Yankee","song_name":"Rompe","album_name":"Barrio Fino en Directo","release_year":2005,"group_or_solo":"Solo","genre":"Reggaeton","ranking":236},
  {"artist_name":"Nelly Furtado","song_name":"Say It Right","album_name":"Loose","release_year":2006,"group_or_solo":"Solo","genre":"Pop","ranking":237},
  {"artist_name":"Shawn Mendes","song_name":"Stitches","album_name":"Handwritten","release_year":2015,"group_or_solo":"Solo","genre":"Pop","ranking":238},
  {"artist_name":"Rihanna","song_name":"Umbrella","album_name":"Good Girl Gone Bad","release_year":2007,"group_or_solo":"Solo","genre":"Pop|R&B","ranking":239},
  {"artist_name":"Bruno Mars","song_name":"Just the Way You Are","album_name":"Doo-Wops & Hooligans","release_year":2010,"group_or_solo":"Solo","genre":"Pop","ranking":240},
  {"artist_name":"Arctic Monkeys","song_name":"Do I Wanna Know?","album_name":"AM","release_year":2013,"group_or_solo":"Group","genre":"Alternative Rock","ranking":241},
  {"artist_name":"Oasis","song_name":"Wonderwall","album_name":"(What's the Story) Morning Glory?","release_year":1995,"group_or_solo":"Group","genre":"Britpop","ranking":242},
  {"artist_name":"Red Hot Chili Peppers","song_name":"Californication","album_name":"Californication","release_year":1999,"group_or_solo":"Group","genre":"Alternative Rock","ranking":243},
  {"artist_name":"Foo Fighters","song_name":"Everlong","album_name":"The Colour and the Shape","release_year":1997,"group_or_solo":"Group","genre":"Rock","ranking":244},
  {"artist_name":"Nirvana","song_name":"Smells Like Teen Spirit","album_name":"Nevermind","release_year":1991,"group_or_solo":"Group","genre":"Grunge","ranking":245},
  {"artist_name":"Shakira","song_name":"Whenever, Wherever","album_name":"Laundry Service","release_year":2001,"group_or_solo":"Solo","genre":"Pop|Latin","ranking":246},
  {"artist_name":"Juanes","song_name":"La Camisa Negra","album_name":"Mi Sangre","release_year":2004,"group_or_solo":"Solo","genre":"Latin Pop","ranking":247},
  {"artist_name":"Kylie Minogue","song_name":"Can't Get You Out of My Head","album_name":"Fever","release_year":2001,"group_or_solo":"Solo","genre":"Pop","ranking":248},
  {"artist_name":"Seal","song_name":"Kiss from a Rose","album_name":"Seal II","release_year":1994,"group_or_solo":"Solo","genre":"Pop","ranking":249},
  {"artist_name":"Jamiroquai","song_name":"Virtual Insanity","album_name":"Travelling Without Moving","release_year":1996,"group_or_solo":"Group","genre":"Funk|Pop","ranking":250}
];
