const exitos = [{"artist_name":"Linc Kingsnod","song_name":"curae nulla dapibus dolor","album_name":null,"release_year":null,"group_or_solo":"Group","genre":"Country"},
{"artist_name":"Cristy Guage","song_name":"condimentum id luctus nec molestie","album_name":"Mr","release_year":1999,"group_or_solo":"Solo","genre":"R&B"},
{"artist_name":"Kelli Farren","song_name":"blandit lacinia erat vestibulum sed magna at nunc","album_name":"Mrs","release_year":1926,"group_or_solo":"Solo","genre":"R&B"},
{"artist_name":"Raul Degli Abbati","song_name":"maecenas rhoncus aliquam lacus morbi quis tortor id","album_name":null,"release_year":1935,"group_or_solo":"Group","genre":"Country"},
{"artist_name":"Jesse Shepherd","song_name":"purus phasellus in felis donec semper sapien","album_name":"Mr","release_year":1935,"group_or_solo":"Group","genre":"Hip Hop"},
{"artist_name":"Shirley Ledbury","song_name":"sit amet nulla quisque arcu libero rutrum","album_name":null,"release_year":1903,"group_or_solo":"Group","genre":"Pop"},
{"artist_name":"Mehetabel O'Doherty","song_name":"justo morbi ut odio cras mi","album_name":"Dr","release_year":2004,"group_or_solo":"Group","genre":"Rock"},
{"artist_name":"Asia Van den Hof","song_name":"quam pede lobortis ligula sit amet eleifend pede libero","album_name":"Mr","release_year":null,"group_or_solo":"Solo","genre":"R&B"},
{"artist_name":"Janet Janousek","song_name":"tempus vel pede morbi porttitor lorem","album_name":null,"release_year":1963,"group_or_solo":"Solo","genre":"Country"},
{"artist_name":"Ollie Powling","song_name":"vulputate luctus cum sociis","album_name":null,"release_year":2017,"group_or_solo":"Solo","genre":"Pop"},
{"artist_name":"Cyrus Grisedale","song_name":"at turpis donec posuere metus","album_name":null,"release_year":1935,"group_or_solo":"Solo","genre":"Hip Hop"},
{"artist_name":"Merrick Westley","song_name":"ut massa volutpat convallis morbi odio","album_name":"Ms","release_year":1926,"group_or_solo":"Group","genre":"Country"},
{"artist_name":"Joe Culwen","song_name":"mauris eget massa tempor convallis nulla neque libero convallis eget","album_name":"Rev","release_year":1968,"group_or_solo":"Group","genre":"R&B"},
{"artist_name":"Kristo Quinney","song_name":"volutpat dui maecenas tristique est et tempus","album_name":"Ms","release_year":1977,"group_or_solo":"Solo","genre":"Hip Hop"},
{"artist_name":"Miner Yushkov","song_name":"nullam sit amet turpis","album_name":"Dr","release_year":2001,"group_or_solo":"Solo","genre":"Pop"},
{"artist_name":"Wade Feary","song_name":"turpis donec posuere metus vitae ipsum aliquam non","album_name":"Rev","release_year":1940,"group_or_solo":"Solo","genre":"Pop"},
{"artist_name":"Alejandro McAnalley","song_name":"sem mauris laoreet ut rhoncus aliquet pulvinar sed","album_name":"Rev","release_year":null,"group_or_solo":"Solo","genre":"Pop"},
{"artist_name":"Ashleigh Bladon","song_name":"vestibulum eget vulputate ut ultrices vel augue","album_name":"Rev","release_year":1930,"group_or_solo":"Group","genre":"Hip Hop"},
{"artist_name":"Dante Gravener","song_name":"montes nascetur ridiculus mus vivamus vestibulum sagittis sapien","album_name":"Ms","release_year":null,"group_or_solo":"Group","genre":"Hip Hop"},
{"artist_name":"Bartholomeo Sterman","song_name":"felis eu sapien cursus vestibulum proin","album_name":null,"release_year":null,"group_or_solo":"Group","genre":"R&B"},
{"artist_name":"Ephrem Wollers","song_name":"congue risus semper porta volutpat quam pede lobortis ligula","album_name":"Honorable","release_year":1938,"group_or_solo":"Group","genre":"Pop"},
{"artist_name":"Roarke Congdon","song_name":"placerat praesent blandit nam nulla integer","album_name":"Mrs","release_year":1954,"group_or_solo":"Group","genre":"Hip Hop"},
{"artist_name":"Raphael Splevings","song_name":"id turpis integer aliquet massa id lobortis convallis tortor risus","album_name":"Honorable","release_year":1907,"group_or_solo":"Solo","genre":"R&B"},
{"artist_name":"Misty Wannop","song_name":"sapien cum sociis natoque penatibus et magnis dis parturient montes","album_name":"Ms","release_year":1978,"group_or_solo":"Solo","genre":"Hip Hop"},
{"artist_name":"Konstantine Gledstane","song_name":"nibh in hac habitasse platea dictumst aliquam","album_name":null,"release_year":1982,"group_or_solo":"Group","genre":"R&B"},
{"artist_name":"Nev Wortt","song_name":"et magnis dis parturient montes nascetur","album_name":"Mr","release_year":null,"group_or_solo":"Solo","genre":"Rock"},
{"artist_name":"Aldridge Allom","song_name":"orci luctus et ultrices posuere cubilia curae donec pharetra magna","album_name":null,"release_year":1953,"group_or_solo":"Group","genre":"Pop"},
{"artist_name":"Merrie Patullo","song_name":"congue elementum in hac habitasse platea dictumst morbi","album_name":"Mrs","release_year":1951,"group_or_solo":"Solo","genre":"R&B"},
{"artist_name":"Ethyl Darch","song_name":"magna bibendum imperdiet nullam orci pede venenatis","album_name":"Honorable","release_year":null,"group_or_solo":"Solo","genre":"Country"},
{"artist_name":"Kial Lalonde","song_name":"interdum mauris ullamcorper purus","album_name":null,"release_year":1917,"group_or_solo":"Solo","genre":"R&B"},
{"artist_name":"Shauna Lealle","song_name":"vestibulum aliquet ultrices erat","album_name":"Mrs","release_year":1992,"group_or_solo":"Solo","genre":"R&B"},
{"artist_name":"Lavinie Harms","song_name":"ipsum primis in faucibus orci luctus et ultrices","album_name":"Mr","release_year":1985,"group_or_solo":"Group","genre":"Hip Hop"},
{"artist_name":"Haskell Scorey","song_name":"interdum eu tincidunt in","album_name":"Ms","release_year":2003,"group_or_solo":"Group","genre":"Pop"},
{"artist_name":"Doralia Hubner","song_name":"posuere cubilia curae donec","album_name":null,"release_year":1936,"group_or_solo":"Solo","genre":"Country"},
{"artist_name":"Bianka Waycot","song_name":"elementum eu interdum eu tincidunt in leo maecenas pulvinar","album_name":null,"release_year":2009,"group_or_solo":"Solo","genre":"Rock"},
{"artist_name":"Allissa Landsman","song_name":"ante nulla justo aliquam quis turpis","album_name":"Ms","release_year":2000,"group_or_solo":"Group","genre":"Country"},
{"artist_name":"Beverlee Traite","song_name":"est quam pharetra magna ac consequat metus sapien ut nunc","album_name":"Rev","release_year":1902,"group_or_solo":"Group","genre":"Rock"},
{"artist_name":"Harlan Semeradova","song_name":"donec ut dolor morbi vel lectus","album_name":"Honorable","release_year":1980,"group_or_solo":"Solo","genre":"Pop"},
{"artist_name":"Marilin Fussell","song_name":"et ultrices posuere cubilia","album_name":null,"release_year":null,"group_or_solo":"Group","genre":"R&B"},
{"artist_name":"Guntar Formigli","song_name":"ut nunc vestibulum ante ipsum primis in faucibus orci","album_name":null,"release_year":1939,"group_or_solo":"Solo","genre":"Hip Hop"},
{"artist_name":"Ingelbert Rowlstone","song_name":"dapibus dolor vel est","album_name":"Mrs","release_year":null,"group_or_solo":"Group","genre":"Pop"},
{"artist_name":"Deeyn Shotboulte","song_name":"ipsum primis in faucibus orci luctus et ultrices","album_name":"Dr","release_year":1927,"group_or_solo":"Group","genre":"Rock"},
{"artist_name":"Wat Bracci","song_name":"eget massa tempor convallis nulla neque","album_name":"Ms","release_year":1964,"group_or_solo":"Solo","genre":"Rock"},
{"artist_name":"Hunfredo Gonsalvez","song_name":"cras pellentesque volutpat dui maecenas","album_name":"Rev","release_year":null,"group_or_solo":"Solo","genre":"Rock"},
{"artist_name":"Murvyn Bydaway","song_name":"volutpat eleifend donec ut","album_name":"Honorable","release_year":1991,"group_or_solo":"Group","genre":"Rock"},
{"artist_name":"Avis Pawelke","song_name":"praesent blandit nam nulla integer pede justo lacinia eget","album_name":"Ms","release_year":1926,"group_or_solo":"Group","genre":"Hip Hop"},
{"artist_name":"Lynnette Canto","song_name":"purus sit amet nulla quisque arcu libero rutrum","album_name":"Dr","release_year":1940,"group_or_solo":"Solo","genre":"Rock"},
{"artist_name":"Ugo Drakeford","song_name":"quam pharetra magna ac consequat metus sapien ut nunc vestibulum","album_name":"Mrs","release_year":1970,"group_or_solo":"Group","genre":"R&B"},
{"artist_name":"Albie Dulling","song_name":"nulla ut erat id mauris vulputate elementum","album_name":"Honorable","release_year":2018,"group_or_solo":"Solo","genre":"Pop"},
{"artist_name":"Tim Kynoch","song_name":"ut massa quis augue luctus tincidunt nulla","album_name":"Dr","release_year":null,"group_or_solo":"Group","genre":"Rock"},
{"artist_name":"Rowe Woolward","song_name":"nisi venenatis tristique fusce congue diam","album_name":"Ms","release_year":null,"group_or_solo":"Solo","genre":"Pop"},
{"artist_name":"Damien Duffie","song_name":"pulvinar lobortis est phasellus sit amet","album_name":"Ms","release_year":1975,"group_or_solo":"Group","genre":"Country"},
{"artist_name":"Melisenda Pennycuick","song_name":"sapien iaculis congue vivamus","album_name":"Mrs","release_year":null,"group_or_solo":"Solo","genre":"Rock"},
{"artist_name":"Cherice Spivie","song_name":"aenean sit amet justo morbi ut odio cras mi","album_name":"Dr","release_year":1980,"group_or_solo":"Group","genre":"Country"},
{"artist_name":"Cybil Pavinese","song_name":"proin leo odio porttitor id consequat in consequat","album_name":"Dr","release_year":1940,"group_or_solo":"Solo","genre":"R&B"},
{"artist_name":"Theresa Lindenstrauss","song_name":"at velit vivamus vel","album_name":"Mr","release_year":1977,"group_or_solo":"Solo","genre":"Rock"},
{"artist_name":"Neille Obert","song_name":"ut nulla sed accumsan felis ut at dolor quis odio","album_name":null,"release_year":null,"group_or_solo":"Group","genre":"Pop"},
{"artist_name":"Miran McIlvaney","song_name":"in hac habitasse platea dictumst maecenas","album_name":"Rev","release_year":2009,"group_or_solo":"Group","genre":"Hip Hop"},
{"artist_name":"Astrix Befroy","song_name":"sed justo pellentesque viverra pede ac","album_name":"Rev","release_year":1927,"group_or_solo":"Group","genre":"R&B"},
{"artist_name":"Ignace Halversen","song_name":"maecenas tristique est et tempus semper est","album_name":"Mr","release_year":1902,"group_or_solo":"Solo","genre":"Rock"},
{"artist_name":"Jules Cosh","song_name":"in faucibus orci luctus et","album_name":null,"release_year":null,"group_or_solo":"Solo","genre":"Country"},
{"artist_name":"Stuart Khotler","song_name":"sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl","album_name":"Rev","release_year":1905,"group_or_solo":"Group","genre":"R&B"},
{"artist_name":"Flori MacIver","song_name":"quis libero nullam sit amet turpis","album_name":"Mr","release_year":null,"group_or_solo":"Solo","genre":"Country"},
{"artist_name":"Annie Mansel","song_name":"massa id nisl venenatis lacinia aenean","album_name":"Rev","release_year":1911,"group_or_solo":"Group","genre":"Pop"},
{"artist_name":"Alexandra Wealleans","song_name":"morbi porttitor lorem id ligula suspendisse ornare","album_name":"Ms","release_year":1949,"group_or_solo":"Group","genre":"Country"},
{"artist_name":"Englebert Bensusan","song_name":"eget orci vehicula condimentum curabitur in libero ut massa volutpat","album_name":null,"release_year":null,"group_or_solo":"Solo","genre":"R&B"},
{"artist_name":"Eben Jeanesson","song_name":"sapien ut nunc vestibulum ante ipsum primis in faucibus orci","album_name":"Rev","release_year":1913,"group_or_solo":"Solo","genre":"R&B"},
{"artist_name":"Cchaddie Ewin","song_name":"sapien a libero nam dui proin leo odio porttitor","album_name":"Rev","release_year":1946,"group_or_solo":"Solo","genre":"Country"},
{"artist_name":"Wit Charer","song_name":"ullamcorper augue a suscipit nulla elit ac","album_name":"Ms","release_year":null,"group_or_solo":"Solo","genre":"Country"},
{"artist_name":"Pepita Di Pietro","song_name":"tellus in sagittis dui vel nisl duis ac","album_name":"Rev","release_year":1912,"group_or_solo":"Group","genre":"Country"},
{"artist_name":"Laurens Hall","song_name":"vulputate vitae nisl aenean lectus pellentesque","album_name":"Dr","release_year":1970,"group_or_solo":"Group","genre":"Hip Hop"},
{"artist_name":"Martguerita Owbridge","song_name":"nam ultrices libero non mattis","album_name":"Honorable","release_year":null,"group_or_solo":"Solo","genre":"Hip Hop"},
{"artist_name":"Loralyn Goatcher","song_name":"in tempus sit amet sem","album_name":"Dr","release_year":null,"group_or_solo":"Group","genre":"Pop"},
{"artist_name":"Enid Beswetherick","song_name":"molestie sed justo pellentesque viverra pede ac diam cras pellentesque","album_name":"Mr","release_year":1935,"group_or_solo":"Solo","genre":"Pop"},
{"artist_name":"Kippar Townrow","song_name":"at ipsum ac tellus semper interdum mauris ullamcorper purus sit","album_name":"Mrs","release_year":null,"group_or_solo":"Solo","genre":"Rock"},
{"artist_name":"Ed Seif","song_name":"augue luctus tincidunt nulla mollis molestie lorem","album_name":"Rev","release_year":null,"group_or_solo":"Solo","genre":"R&B"},
{"artist_name":"Julita Lettington","song_name":"neque duis bibendum morbi non quam nec dui luctus rutrum","album_name":"Ms","release_year":1968,"group_or_solo":"Solo","genre":"Pop"},
{"artist_name":"Jamill Markovich","song_name":"risus dapibus augue vel","album_name":"Dr","release_year":1945,"group_or_solo":"Group","genre":"Country"},
{"artist_name":"Findley Greenley","song_name":"at turpis a pede posuere nonummy integer non velit donec","album_name":"Mr","release_year":null,"group_or_solo":"Group","genre":"Pop"},
{"artist_name":"Felike Driutti","song_name":"tortor duis mattis egestas metus aenean fermentum donec ut mauris","album_name":null,"release_year":null,"group_or_solo":"Group","genre":"Country"},
{"artist_name":"Ewart Edgley","song_name":"nibh fusce lacus purus aliquet at feugiat non pretium quis","album_name":"Mrs","release_year":1950,"group_or_solo":"Group","genre":"Pop"},
{"artist_name":"Easter Eul","song_name":"enim sit amet nunc viverra dapibus nulla","album_name":"Mr","release_year":1980,"group_or_solo":"Group","genre":"R&B"},
{"artist_name":"Kearney Barrass","song_name":"id mauris vulputate elementum","album_name":"Mr","release_year":1968,"group_or_solo":"Group","genre":"Hip Hop"},
{"artist_name":"Sal Scone","song_name":"cum sociis natoque penatibus et magnis dis parturient montes nascetur","album_name":"Mr","release_year":null,"group_or_solo":"Group","genre":"Country"},
{"artist_name":"Sandie Wildin","song_name":"pede justo eu massa donec dapibus duis at","album_name":"Rev","release_year":null,"group_or_solo":"Solo","genre":"Pop"},
{"artist_name":"Davie Coston","song_name":"molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget","album_name":"Ms","release_year":1924,"group_or_solo":"Group","genre":"Hip Hop"},
{"artist_name":"Gladys Edgeon","song_name":"amet turpis elementum ligula vehicula consequat morbi a","album_name":"Mr","release_year":1936,"group_or_solo":"Solo","genre":"Pop"},
{"artist_name":"Omero Cowdroy","song_name":"ac consequat metus sapien ut","album_name":"Mr","release_year":2010,"group_or_solo":"Group","genre":"Rock"},
{"artist_name":"Vin Bendixen","song_name":"vel accumsan tellus nisi eu orci mauris lacinia","album_name":null,"release_year":1932,"group_or_solo":"Solo","genre":"Country"},
{"artist_name":"Bebe Bawme","song_name":"habitasse platea dictumst maecenas","album_name":"Ms","release_year":1901,"group_or_solo":"Solo","genre":"Pop"},
{"artist_name":"Alasdair Stout","song_name":"justo lacinia eget tincidunt eget tempus vel pede morbi porttitor","album_name":"Mr","release_year":1949,"group_or_solo":"Solo","genre":"Country"},
{"artist_name":"Barney Schimpke","song_name":"et ultrices posuere cubilia curae duis faucibus accumsan","album_name":null,"release_year":1974,"group_or_solo":"Solo","genre":"R&B"},
{"artist_name":"Ashely Hechlin","song_name":"sapien quis libero nullam sit amet turpis elementum ligula vehicula","album_name":"Dr","release_year":1982,"group_or_solo":"Solo","genre":"Country"},
{"artist_name":"Clim Hawsby","song_name":"libero non mattis pulvinar nulla pede ullamcorper augue a suscipit","album_name":"Dr","release_year":null,"group_or_solo":"Group","genre":"Pop"},
{"artist_name":"Sybilla Schnitter","song_name":"sociis natoque penatibus et magnis","album_name":"Mr","release_year":2011,"group_or_solo":"Solo","genre":"Rock"},
{"artist_name":"Aldis Tallquist","song_name":"pretium iaculis justo in hac habitasse","album_name":"Dr","release_year":1994,"group_or_solo":"Solo","genre":"Pop"},
{"artist_name":"Agace Garforth","song_name":"vel nisl duis ac nibh fusce lacus purus aliquet","album_name":"Honorable","release_year":null,"group_or_solo":"Group","genre":"Hip Hop"},
{"artist_name":"Gill Ovett","song_name":"dui maecenas tristique est et tempus semper est quam pharetra","album_name":null,"release_year":1943,"group_or_solo":"Group","genre":"R&B"},
{"artist_name":"Tymon Avramow","song_name":"ullamcorper purus sit amet nulla quisque arcu libero rutrum","album_name":"Rev","release_year":1902,"group_or_solo":"Solo","genre":"R&B"},
{"artist_name":"Petey Folshom","song_name":"aliquet maecenas leo odio condimentum id luctus nec","album_name":null,"release_year":1973,"group_or_solo":"Group","genre":"Pop"},
{"artist_name":"Cody Picheford","song_name":"ante vestibulum ante ipsum primis","album_name":"Honorable","release_year":null,"group_or_solo":"Group","genre":"Rock"},
{"artist_name":"Dusty Devil","song_name":"morbi non quam nec dui luctus rutrum nulla tellus","album_name":"Ms","release_year":1914,"group_or_solo":"Solo","genre":"R&B"},
{"artist_name":"Vladimir Donke","song_name":"vestibulum quam sapien varius ut blandit non","album_name":"Rev","release_year":null,"group_or_solo":"Group","genre":"Pop"},
{"artist_name":"Archaimbaud Guilfoyle","song_name":"justo morbi ut odio cras mi pede malesuada","album_name":null,"release_year":1922,"group_or_solo":"Group","genre":"Rock"},
{"artist_name":"Aubine Prime","song_name":"eu interdum eu tincidunt in leo maecenas pulvinar lobortis","album_name":"Honorable","release_year":1940,"group_or_solo":"Solo","genre":"Pop"},
{"artist_name":"Lemar Feaviour","song_name":"felis ut at dolor quis odio consequat varius","album_name":"Mr","release_year":1902,"group_or_solo":"Solo","genre":"Country"},
{"artist_name":"Bald Koene","song_name":"sapien arcu sed augue aliquam erat volutpat","album_name":"Honorable","release_year":1908,"group_or_solo":"Solo","genre":"Pop"},
{"artist_name":"Thorsten Friskey","song_name":"sem praesent id massa id","album_name":null,"release_year":null,"group_or_solo":"Solo","genre":"Pop"},
{"artist_name":"Giralda Tarbet","song_name":"elit proin interdum mauris non ligula pellentesque ultrices phasellus id","album_name":"Ms","release_year":null,"group_or_solo":"Group","genre":"Country"},
{"artist_name":"Caresse Kenshole","song_name":"dapibus at diam nam tristique tortor eu","album_name":"Mrs","release_year":2002,"group_or_solo":"Group","genre":"Pop"},
{"artist_name":"Lynne Pedroli","song_name":"vivamus tortor duis mattis egestas","album_name":"Rev","release_year":null,"group_or_solo":"Solo","genre":"Country"},
{"artist_name":"Colver Tyndall","song_name":"bibendum imperdiet nullam orci pede venenatis non sodales","album_name":"Mrs","release_year":null,"group_or_solo":"Solo","genre":"R&B"},
{"artist_name":"Sheffy Cotte","song_name":"varius ut blandit non interdum in ante vestibulum ante ipsum","album_name":"Honorable","release_year":null,"group_or_solo":"Solo","genre":"R&B"},
{"artist_name":"Hugues Beswick","song_name":"elit proin risus praesent","album_name":null,"release_year":1998,"group_or_solo":"Solo","genre":"R&B"},
{"artist_name":"Margot Prescote","song_name":"porta volutpat erat quisque erat eros viverra","album_name":"Mrs","release_year":1972,"group_or_solo":"Solo","genre":"Rock"},
{"artist_name":"Winnah Hooks","song_name":"accumsan felis ut at dolor","album_name":"Mr","release_year":1971,"group_or_solo":"Solo","genre":"R&B"},
{"artist_name":"Margalo Biasotti","song_name":"a libero nam dui proin leo","album_name":"Rev","release_year":1985,"group_or_solo":"Solo","genre":"R&B"},
{"artist_name":"Hunfredo O'Kynsillaghe","song_name":"nulla nunc purus phasellus in","album_name":"Mr","release_year":null,"group_or_solo":"Group","genre":"R&B"},
{"artist_name":"Juditha Klass","song_name":"sem sed sagittis nam congue risus semper porta","album_name":"Dr","release_year":1949,"group_or_solo":"Group","genre":"Pop"},
{"artist_name":"Merlina Annis","song_name":"luctus et ultrices posuere cubilia curae duis faucibus accumsan","album_name":null,"release_year":1944,"group_or_solo":"Solo","genre":"Rock"},
{"artist_name":"Gal Creese","song_name":"pede ullamcorper augue a suscipit","album_name":"Rev","release_year":1925,"group_or_solo":"Solo","genre":"R&B"},
{"artist_name":"Vally Sainte Paul","song_name":"rutrum neque aenean auctor gravida sem praesent","album_name":"Rev","release_year":null,"group_or_solo":"Group","genre":"Pop"},
{"artist_name":"Anastasia Judgkins","song_name":"purus aliquet at feugiat","album_name":"Dr","release_year":1963,"group_or_solo":"Solo","genre":"Hip Hop"},
{"artist_name":"Janeva Shilburne","song_name":"convallis morbi odio odio elementum","album_name":"Dr","release_year":1978,"group_or_solo":"Solo","genre":"Country"},
{"artist_name":"Antonino Steinson","song_name":"consequat ut nulla sed accumsan felis","album_name":"Dr","release_year":1907,"group_or_solo":"Solo","genre":"Rock"},
{"artist_name":"Derk Abbet","song_name":"sapien varius ut blandit non interdum in ante vestibulum ante","album_name":null,"release_year":1940,"group_or_solo":"Group","genre":"R&B"},
{"artist_name":"Hertha Lambden","song_name":"tincidunt eu felis fusce posuere felis sed lacus morbi sem","album_name":"Dr","release_year":1970,"group_or_solo":"Group","genre":"Pop"},
{"artist_name":"Blanche Dreus","song_name":"ligula vehicula consequat morbi a","album_name":"Dr","release_year":1995,"group_or_solo":"Solo","genre":"R&B"},
{"artist_name":"Javier Quigg","song_name":"luctus et ultrices posuere","album_name":null,"release_year":1906,"group_or_solo":"Group","genre":"Rock"},
{"artist_name":"Clary Robertshaw","song_name":"lorem id ligula suspendisse ornare consequat lectus","album_name":"Mrs","release_year":1910,"group_or_solo":"Solo","genre":"R&B"},
{"artist_name":"Mariann Leitche","song_name":"curae donec pharetra magna vestibulum","album_name":null,"release_year":1988,"group_or_solo":"Group","genre":"Hip Hop"},
{"artist_name":"Andris Edgerton","song_name":"purus aliquet at feugiat non pretium quis lectus suspendisse","album_name":"Mrs","release_year":1930,"group_or_solo":"Group","genre":"R&B"},
{"artist_name":"Darcie Lillywhite","song_name":"ligula sit amet eleifend pede","album_name":null,"release_year":1999,"group_or_solo":"Group","genre":"Country"},
{"artist_name":"Nataniel Henricsson","song_name":"quis turpis sed ante vivamus tortor duis mattis egestas metus","album_name":null,"release_year":1999,"group_or_solo":"Solo","genre":"Country"},
{"artist_name":"Floria Weber","song_name":"vel dapibus at diam nam tristique tortor","album_name":"Rev","release_year":2014,"group_or_solo":"Group","genre":"Rock"},
{"artist_name":"Cosme Fabb","song_name":"lectus in quam fringilla","album_name":"Rev","release_year":1980,"group_or_solo":"Group","genre":"Rock"},
{"artist_name":"Franni Schustl","song_name":"vel enim sit amet nunc viverra dapibus nulla","album_name":"Mr","release_year":null,"group_or_solo":"Group","genre":"Country"},
{"artist_name":"Mella Worshall","song_name":"diam nam tristique tortor eu","album_name":null,"release_year":2009,"group_or_solo":"Group","genre":"Hip Hop"},
{"artist_name":"Beryl Painten","song_name":"vel pede morbi porttitor","album_name":"Dr","release_year":null,"group_or_solo":"Solo","genre":"Rock"},
{"artist_name":"Rhea Penkethman","song_name":"rutrum neque aenean auctor gravida","album_name":"Dr","release_year":null,"group_or_solo":"Group","genre":"Pop"},
{"artist_name":"Howard Domenichini","song_name":"ultrices enim lorem ipsum dolor","album_name":null,"release_year":1969,"group_or_solo":"Group","genre":"Rock"},
{"artist_name":"Rivkah Duddridge","song_name":"rhoncus aliquet pulvinar sed nisl nunc rhoncus dui","album_name":"Dr","release_year":1956,"group_or_solo":"Solo","genre":"Pop"},
{"artist_name":"Clerissa Bills","song_name":"morbi vestibulum velit id","album_name":"Dr","release_year":1906,"group_or_solo":"Solo","genre":"Hip Hop"},
{"artist_name":"Scotty Saller","song_name":"mattis egestas metus aenean fermentum donec ut","album_name":"Dr","release_year":null,"group_or_solo":"Group","genre":"Rock"},
{"artist_name":"Abagael Calliss","song_name":"elementum nullam varius nulla facilisi cras non velit nec nisi","album_name":"Mrs","release_year":1946,"group_or_solo":"Solo","genre":"Rock"},
{"artist_name":"Kym Dannatt","song_name":"sit amet eros suspendisse accumsan tortor quis turpis","album_name":"Ms","release_year":null,"group_or_solo":"Solo","genre":"Pop"},
{"artist_name":"Goddart Songust","song_name":"faucibus orci luctus et ultrices posuere cubilia curae duis","album_name":"Dr","release_year":1992,"group_or_solo":"Group","genre":"R&B"},
{"artist_name":"Harlie Takis","song_name":"velit donec diam neque vestibulum eget vulputate ut ultrices vel","album_name":"Ms","release_year":1910,"group_or_solo":"Group","genre":"Country"},
{"artist_name":"Jerrine Gerauld","song_name":"tristique fusce congue diam id ornare imperdiet","album_name":"Mrs","release_year":2005,"group_or_solo":"Solo","genre":"Pop"},
{"artist_name":"Ginni Uvedale","song_name":"nisl nunc rhoncus dui","album_name":null,"release_year":2006,"group_or_solo":"Group","genre":"Country"}]