const listaVuelos = [
  {
    vuelo: "QL584",
    compañia: "Finnair",
    origen: "Barcelona",
    destino: "Stockholm",
    precio: 120.52,
    tarifa: "infantil",
  },
  {
    vuelo: "XY201",
    compañia: "Lufthansa",
    origen: "Lisbon",
    destino: "Stockholm",
    precio: 140.71,
    tarifa: "business",
  },
  {
    vuelo: "VS429",
    compañia: "EasyJet",
    origen: "Paris",
    destino: "Dublin",
    precio: 194.16,
    tarifa: "business",
  },
  {
    vuelo: "PF671",
    compañia: "EasyJet",
    origen: "Madrid",
    destino: "Madrid",
    precio: 167.47,
    tarifa: "business",
  },
  {
    vuelo: "NJ878",
    compañia: "KLM",
    origen: "Rome",
    destino: "Madrid",
    precio: 373.34,
    tarifa: "tercera edad",
  },
  {
    vuelo: "CO922",
    compañia: "SAS",
    origen: "Lisbon",
    destino: "Berlin",
    precio: 457.72,
    tarifa: "infantil",
  },
  {
    vuelo: "CS231",
    compañia: "Air Europa",
    origen: "London",
    destino: "Paris",
    precio: 136.68,
    tarifa: "business",
  },
  {
    vuelo: "ME181",
    compañia: "Norwegian Air",
    origen: "Lisbon",
    destino: "Athens",
    precio: 219.19,
    tarifa: "business",
  },
  {
    vuelo: "CC406",
    compañia: "Air Europa",
    origen: "Dublin",
    destino: "Athens",
    precio: 517.79,
    tarifa: "infantil",
  },
  {
    vuelo: "QF441",
    compañia: "Finnair",
    origen: "Rome",
    destino: "Stockholm",
    precio: 241.6,
    tarifa: "business",
  },
  {
    vuelo: "OO302",
    compañia: "SAS",
    origen: "London",
    destino: "Oslo",
    precio: 502.97,
    tarifa: "business",
  },
  {
    vuelo: "YK526",
    compañia: "EasyJet",
    origen: "Amsterdam",
    destino: "Rome",
    precio: 562.51,
    tarifa: "infantil",
  },
  {
    vuelo: "YP292",
    compañia: "EasyJet",
    origen: "Lisbon",
    destino: "Dublin",
    precio: 364.66,
    tarifa: "business",
  },
  {
    vuelo: "NI298",
    compañia: "Finnair",
    origen: "Madrid",
    destino: "Copenhage",
    precio: 172.85,
    tarifa: "infantil",
  },
  {
    vuelo: "CO736",
    compañia: "SAS",
    origen: "Lisbon",
    destino: "Paris",
    precio: 160.68,
    tarifa: "tercera edad",
  },
  {
    vuelo: "IG230",
    compañia: "Air Europa",
    origen: "London",
    destino: "Stockholm",
    precio: 259.71,
    tarifa: "business",
  },
  {
    vuelo: "ED517",
    compañia: "Norwegian Air",
    origen: "Barcelona",
    destino: "Madrid",
    precio: 357.85,
    tarifa: "turista",
  },
  {
    vuelo: "RK249",
    compañia: "Air Europa",
    origen: "Berlin",
    destino: "Vienna",
    precio: 592.72,
    tarifa: "turista",
  },
  {
    vuelo: "SD637",
    compañia: "Finnair",
    origen: "Dublin",
    destino: "Paris",
    precio: 96.77,
    tarifa: "turista",
  },
  {
    vuelo: "AC325",
    compañia: "EasyJet",
    origen: "Rome",
    destino: "Copenhage",
    precio: 210.84,
    tarifa: "business",
  },
  {
    vuelo: "KQ149",
    compañia: "Lufthansa",
    origen: "Amsterdam",
    destino: "Oslo",
    precio: 462.51,
    tarifa: "tercera edad",
  },
  {
    vuelo: "YQ125",
    compañia: "Lufthansa",
    origen: "Amsterdam",
    destino: "Oslo",
    precio: 253.66,
    tarifa: "turista",
  },
  {
    vuelo: "YB265",
    compañia: "Air Europa",
    origen: "Amsterdam",
    destino: "Oslo",
    precio: 261.03,
    tarifa: "infantil",
  },
  {
    vuelo: "LX504",
    compañia: "Finnair",
    origen: "Madrid",
    destino: "Rome",
    precio: 314.95,
    tarifa: "business",
  },
  {
    vuelo: "LL202",
    compañia: "EasyJet",
    origen: "Paris",
    destino: "Paris",
    precio: 316.97,
    tarifa: "business",
  },
  {
    vuelo: "TP066",
    compañia: "British Airways",
    origen: "Amsterdam",
    destino: "Oslo",
    precio: 596.36,
    tarifa: "tercera edad",
  },
  {
    vuelo: "HA021",
    compañia: "Iberia",
    origen: "Berlin",
    destino: "Stockholm",
    precio: 435.62,
    tarifa: "turista",
  },
  {
    vuelo: "UZ030",
    compañia: "Finnair",
    origen: "Lisbon",
    destino: "Athens",
    precio: 80.53,
    tarifa: "tercera edad",
  },
  {
    vuelo: "AP353",
    compañia: "Norwegian Air",
    origen: "London",
    destino: "Vienna",
    precio: 145.84,
    tarifa: "business",
  },
  {
    vuelo: "DU586",
    compañia: "KLM",
    origen: "Amsterdam",
    destino: "Oslo",
    precio: 405.4,
    tarifa: "tercera edad",
  },
  {
    vuelo: "NP613",
    compañia: "Finnair",
    origen: "Vienna",
    destino: "Oslo",
    precio: 550.49,
    tarifa: "turista",
  },
  {
    vuelo: "YD456",
    compañia: "British Airways",
    origen: "Paris",
    destino: "Copenhage",
    precio: 568.36,
    tarifa: "business",
  },
  {
    vuelo: "OE970",
    compañia: "Air Europa",
    origen: "London",
    destino: "Madrid",
    precio: 255.1,
    tarifa: "turista",
  },
  {
    vuelo: "HA088",
    compañia: "Lufthansa",
    origen: "Barcelona",
    destino: "Dublin",
    precio: 179.96,
    tarifa: "turista",
  },
  {
    vuelo: "NV840",
    compañia: "EasyJet",
    origen: "Madrid",
    destino: "Dublin",
    precio: 241.65,
    tarifa: "turista",
  },
  {
    vuelo: "OQ518",
    compañia: "British Airways",
    origen: "Dublin",
    destino: "Oslo",
    precio: 531.75,
    tarifa: "infantil",
  },
  {
    vuelo: "HT050",
    compañia: "EasyJet",
    origen: "Lisbon",
    destino: "Paris",
    precio: 126.12,
    tarifa: "business",
  },
  {
    vuelo: "FX294",
    compañia: "EasyJet",
    origen: "Rome",
    destino: "Berlin",
    precio: 416.52,
    tarifa: "infantil",
  },
  {
    vuelo: "BE624",
    compañia: "EasyJet",
    origen: "Madrid",
    destino: "Madrid",
    precio: 125.48,
    tarifa: "tercera edad",
  },
  {
    vuelo: "SQ939",
    compañia: "Finnair",
    origen: "London",
    destino: "Stockholm",
    precio: 440.56,
    tarifa: "infantil",
  },
  {
    vuelo: "WJ877",
    compañia: "Lufthansa",
    origen: "Amsterdam",
    destino: "Berlin",
    precio: 117.04,
    tarifa: "business",
  },
  {
    vuelo: "VQ516",
    compañia: "Norwegian Air",
    origen: "Rome",
    destino: "Paris",
    precio: 170.85,
    tarifa: "tercera edad",
  },
  {
    vuelo: "ZE164",
    compañia: "British Airways",
    origen: "London",
    destino: "Oslo",
    precio: 231.58,
    tarifa: "business",
  },
  {
    vuelo: "ZX560",
    compañia: "KLM",
    origen: "Amsterdam",
    destino: "Athens",
    precio: 317.13,
    tarifa: "tercera edad",
  },
  {
    vuelo: "IL736",
    compañia: "EasyJet",
    origen: "Rome",
    destino: "Rome",
    precio: 429.0,
    tarifa: "tercera edad",
  },
  {
    vuelo: "JZ367",
    compañia: "Finnair",
    origen: "Lisbon",
    destino: "Copenhage",
    precio: 55.5,
    tarifa: "infantil",
  },
  {
    vuelo: "JY419",
    compañia: "SAS",
    origen: "Dublin",
    destino: "Athens",
    precio: 210.63,
    tarifa: "tercera edad",
  },
  {
    vuelo: "HV680",
    compañia: "Lufthansa",
    origen: "Berlin",
    destino: "Vienna",
    precio: 71.52,
    tarifa: "business",
  },
  {
    vuelo: "IX214",
    compañia: "Air Europa",
    origen: "Lisbon",
    destino: "Oslo",
    precio: 376.25,
    tarifa: "tercera edad",
  },
  {
    vuelo: "ES995",
    compañia: "KLM",
    origen: "Barcelona",
    destino: "Dublin",
    precio: 314.41,
    tarifa: "tercera edad",
  },
];
